# Generated by Django 5.2 on 2026-04-07 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('arquivo', models.FileField(upload_to='anexos/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.BigIntegerField()),
                ('tipo_mime', models.CharField(max_length=100)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario_upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'db_table': 'anexos',
                'ordering': ['-data_upload'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='anexos_content_a7903f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('SUBMIT', 'Submissão'), ('APPROVE', 'Aprovação'), ('REJECT', 'Rejeição'), ('TRANSITION', 'Transição de Status'), ('VIEW', 'Visualização'), ('EXPORT', 'Exportação')], db_index=True, max_length=15)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('modelo', models.CharField(db_index=True, max_length=100)),
                ('objeto_id', models.CharField(max_length=100)),
                ('objeto_repr', models.CharField(max_length=200)),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_novos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('mensagem', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'permissions': [('view_all_logs', 'Pode visualizar todos os logs'), ('export_logs', 'Pode exportar logs')],
                'indexes': [models.Index(fields=['usuario', '-timestamp'], name='audit_logs_usuario_5354f3_idx'), models.Index(fields=['modelo', 'objeto_id'], name='audit_logs_modelo_582775_idx'), models.Index(fields=['acao', '-timestamp'], name='audit_logs_acao_0a635e_idx'), models.Index(fields=['-timestamp'], name='audit_logs_timesta_e93820_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=25)),
                ('status_novo', models.CharField(max_length=25)),
                ('justificativa', models.TextField(blank=True)),
                ('data_transicao', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='projetos.projeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'db_table': 'historico_status',
                'ordering': ['-data_transicao'],
                'indexes': [models.Index(fields=['projeto', '-data_transicao'], name='historico_s_projeto_3c6125_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INFO', 'Informação'), ('ALERTA', 'Alerta'), ('URGENTE', 'Urgente'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], default='INFO', max_length=10)),
                ('status', models.CharField(choices=[('NAO_LIDA', 'Não Lida'), ('LIDA', 'Lida'), ('ARQUIVADA', 'Arquivada')], default='NAO_LIDA', max_length=15)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'notificacoes',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['destinatario', 'status', '-data_criacao'], name='notificacoe_destina_1fa8c7_idx'), models.Index(fields=['destinatario', '-data_criacao'], name='notificacoe_destina_9ec88f_idx')],
            },
        ),
    ]
