# Generated by Django 5.2 on 2026-04-07 00:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=200)),
                ('descricao', models.TextField()),
                ('justificativa', models.TextField()),
                ('objetivos', models.TextField()),
                ('resultados_esperados', models.TextField()),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDO', 'Submetido'), ('EM_AVALIACAO', 'Em Avaliação'), ('EM_VIABILIDADE', 'Em Análise de Viabilidade'), ('EM_PRIORIZACAO', 'Em Priorização'), ('EM_CONSOLIDACAO', 'Em Consolidação'), ('EM_VALIDACAO', 'Em Validação'), ('EM_DELIBERACAO', 'Em Deliberação'), ('AGUARDANDO_COMUNICACAO', 'Aguardando Comunicação'), ('COMUNICADO', 'Comunicado'), ('ACEITO', 'Aceito'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado')], db_index=True, default='RASCUNHO', max_length=25)),
                ('prioridade', models.CharField(blank=True, choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10, null=True)),
                ('data_inicio_prevista', models.DateField(blank=True, null=True)),
                ('data_fim_prevista', models.DateField(blank=True, null=True)),
                ('data_inicio_real', models.DateField(blank=True, null=True)),
                ('data_fim_real', models.DateField(blank=True, null=True)),
                ('orcamento_previsto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('orcamento_realizado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pontuacao_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(110)])),
                ('data_submissao', models.DateTimeField(blank=True, null=True)),
                ('data_aceite', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('demandante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos_demandados', to=settings.AUTH_USER_MODEL)),
                ('gerente_projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_gerenciados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'projetos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('meta', models.CharField(max_length=100)),
                ('valor_atual', models.CharField(blank=True, max_length=100)),
                ('unidade_medida', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'db_table': 'indicadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TERMO_ABERTURA', 'Termo de Abertura'), ('PLANO_PROJETO', 'Plano de Projeto'), ('CRONOGRAMA', 'Cronograma'), ('ORCAMENTO', 'Orçamento'), ('RELATORIO', 'Relatório'), ('ATA', 'Ata de Reunião'), ('OUTRO', 'Outro')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo', models.FileField(upload_to='projetos/documentos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx'])])),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('usuario_upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documentos',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HUMANO', 'Recurso Humano'), ('MATERIAL', 'Material'), ('FINANCEIRO', 'Financeiro'), ('TECNOLOGICO', 'Tecnológico')], max_length=15)),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(max_length=50)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'db_table': 'recursos',
                'ordering': ['tipo', 'descricao'],
            },
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['status', 'ativo'], name='projetos_status_76847d_idx'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['demandante', 'status'], name='projetos_demanda_9de2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['data_submissao'], name='projetos_data_su_a4b125_idx'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['-pontuacao_total'], name='projetos_pontuac_4af6b6_idx'),
        ),
    ]
