# Generated by Django 5.2 on 2026-04-07 00:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=15)),
                ('pontuacao_etapa_a', models.DecimalField(blank=True, decimal_places=2, help_text='Alinhamento Estratégico (0-25 pontos)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('pontuacao_etapa_b', models.DecimalField(blank=True, decimal_places=2, help_text='Impacto e Benefícios (0-25 pontos)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('parecer_tecnico', models.TextField(blank=True)),
                ('recomendacoes', models.TextField(blank=True)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'db_table': 'avaliacoes',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CriterioAvaliacaoA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=200)),
                ('pontuacao', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('justificativa', models.TextField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios_etapa_a', to='avaliacoes.avaliacao')),
            ],
            options={
                'verbose_name': 'Critério Etapa A',
                'verbose_name_plural': 'Critérios Etapa A',
                'db_table': 'criterios_avaliacao_a',
            },
        ),
        migrations.CreateModel(
            name='CriterioAvaliacaoB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=200)),
                ('pontuacao', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('justificativa', models.TextField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios_etapa_b', to='avaliacoes.avaliacao')),
            ],
            options={
                'verbose_name': 'Critério Etapa B',
                'verbose_name_plural': 'Critérios Etapa B',
                'db_table': 'criterios_avaliacao_b',
            },
        ),
        migrations.CreateModel(
            name='Priorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao_etapa_c', models.DecimalField(decimal_places=2, help_text='Critérios Ponderados (0-60 pontos)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('complexidade', models.IntegerField(help_text='1=Muito Baixa, 5=Muito Alta', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('urgencia', models.IntegerField(help_text='1=Muito Baixa, 5=Muito Alta', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impacto_estrategico', models.IntegerField(help_text='1=Muito Baixo, 5=Muito Alto', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('recursos_disponiveis', models.BooleanField(default=False)),
                ('dependencias_externas', models.BooleanField(default=False)),
                ('justificativa', models.TextField()),
                ('observacoes', models.TextField(blank=True)),
                ('data_priorizacao', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorizacoes', to='projetos.projeto')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='priorizacoes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Priorização',
                'verbose_name_plural': 'Priorizações',
                'db_table': 'priorizacoes',
                'ordering': ['-pontuacao_etapa_c', '-data_priorizacao'],
            },
        ),
        migrations.CreateModel(
            name='CriterioPriorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=200)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('pontuacao', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('priorizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='avaliacoes.priorizacao')),
            ],
            options={
                'verbose_name': 'Critério de Priorização',
                'verbose_name_plural': 'Critérios de Priorização',
                'db_table': 'criterios_priorizacao',
            },
        ),
        migrations.CreateModel(
            name='Viabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=15)),
                ('resultado', models.CharField(blank=True, choices=[('VIAVEL', 'Viável'), ('VIAVEL_COM_RESTRICOES', 'Viável com Restrições'), ('INVIAVEL', 'Inviável')], max_length=25, null=True)),
                ('viabilidade_tecnica', models.BooleanField(null=True)),
                ('viabilidade_financeira', models.BooleanField(null=True)),
                ('viabilidade_operacional', models.BooleanField(null=True)),
                ('viabilidade_juridica', models.BooleanField(null=True)),
                ('analise_tecnica', models.TextField(blank=True)),
                ('analise_financeira', models.TextField(blank=True)),
                ('analise_operacional', models.TextField(blank=True)),
                ('analise_juridica', models.TextField(blank=True)),
                ('riscos_identificados', models.TextField(blank=True)),
                ('restricoes', models.TextField(blank=True)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viabilidades_analisadas', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_viabilidade', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Análise de Viabilidade',
                'verbose_name_plural': 'Análises de Viabilidade',
                'db_table': 'viabilidades',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['projeto', 'status'], name='avaliacoes_projeto_2be427_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['avaliador', 'status'], name='avaliacoes_avaliad_dafe8b_idx'),
        ),
        migrations.AddIndex(
            model_name='priorizacao',
            index=models.Index(fields=['projeto'], name='priorizacoe_projeto_0c1620_idx'),
        ),
        migrations.AddIndex(
            model_name='priorizacao',
            index=models.Index(fields=['-pontuacao_etapa_c'], name='priorizacoe_pontuac_59cd84_idx'),
        ),
        migrations.AddIndex(
            model_name='viabilidade',
            index=models.Index(fields=['projeto', 'status'], name='viabilidade_projeto_3c9390_idx'),
        ),
        migrations.AddIndex(
            model_name='viabilidade',
            index=models.Index(fields=['resultado'], name='viabilidade_resulta_ae8c1f_idx'),
        ),
    ]
