# Generated by Django 5.2 on 2026-04-07 00:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aceite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_aceite', models.TextField()),
                ('observacoes', models.TextField(blank=True)),
                ('data_aceite', models.DateTimeField(auto_now_add=True)),
                ('aceito_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceites_realizados', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aceite', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Aceite',
                'verbose_name_plural': 'Aceites',
                'db_table': 'aceites',
                'ordering': ['-data_aceite'],
            },
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(db_index=True)),
                ('periodo', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('EM_CONSOLIDACAO', 'Em Consolidação'), ('EM_VALIDACAO', 'Em Validação'), ('EM_DELIBERACAO', 'Em Deliberação'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='EM_CONSOLIDACAO', max_length=20)),
                ('orcamento_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('data_consolidacao', models.DateTimeField(blank=True, null=True)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('data_deliberacao', models.DateTimeField(blank=True, null=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('gerente_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carteiras_gerenciadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carteira de Projetos',
                'verbose_name_plural': 'Carteiras de Projetos',
                'db_table': 'carteiras',
                'ordering': ['-ano', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Comunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APROVACAO', 'Aprovação de Projeto'), ('REJEICAO', 'Rejeição de Projeto'), ('SOLICITACAO_INFO', 'Solicitação de Informações'), ('NOTIFICACAO', 'Notificação Geral')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADA', 'Enviada'), ('RECEBIDA', 'Recebida')], default='PENDENTE', max_length=15)),
                ('assunto', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('carteira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicacoes', to='carteira.carteira')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicacoes', to='projetos.projeto')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicacoes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicação',
                'verbose_name_plural': 'Comunicações',
                'db_table': 'comunicacoes',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Deliberacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=15)),
                ('decisao', models.TextField()),
                ('justificativa', models.TextField()),
                ('observacoes', models.TextField(blank=True)),
                ('data_deliberacao', models.DateTimeField(auto_now_add=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberacoes', to='carteira.carteira')),
                ('deliberador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliberacoes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deliberação',
                'verbose_name_plural': 'Deliberações',
                'db_table': 'deliberacoes',
                'ordering': ['-data_deliberacao'],
            },
        ),
        migrations.CreateModel(
            name='ProjetoCarteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao_ranking', models.IntegerField(blank=True, null=True)),
                ('incluido_carteira', models.BooleanField(default=True)),
                ('justificativa_inclusao', models.TextField(blank=True)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='carteira.carteira')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteiras', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Projeto na Carteira',
                'verbose_name_plural': 'Projetos na Carteira',
                'db_table': 'projetos_carteira',
                'ordering': ['posicao_ranking', '-projeto__pontuacao_total'],
            },
        ),
        migrations.CreateModel(
            name='Validacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=15)),
                ('parecer', models.TextField()),
                ('recomendacoes', models.TextField(blank=True)),
                ('ajustes_solicitados', models.TextField(blank=True)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validacoes', to='carteira.carteira')),
                ('validador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validacoes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validação',
                'verbose_name_plural': 'Validações',
                'db_table': 'validacoes',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='carteira',
            index=models.Index(fields=['ano', 'periodo'], name='carteiras_ano_ed0c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='carteira',
            index=models.Index(fields=['status'], name='carteiras_status_fdef1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carteira',
            unique_together={('ano', 'periodo')},
        ),
        migrations.AddIndex(
            model_name='comunicacao',
            index=models.Index(fields=['destinatario', 'status'], name='comunicacoe_destina_955f71_idx'),
        ),
        migrations.AddIndex(
            model_name='comunicacao',
            index=models.Index(fields=['projeto', 'tipo'], name='comunicacoe_projeto_e147d5_idx'),
        ),
        migrations.AddIndex(
            model_name='deliberacao',
            index=models.Index(fields=['carteira', 'status'], name='deliberacoe_carteir_fd1235_idx'),
        ),
        migrations.AddIndex(
            model_name='projetocarteira',
            index=models.Index(fields=['carteira', 'incluido_carteira'], name='projetos_ca_carteir_decb4e_idx'),
        ),
        migrations.AddIndex(
            model_name='projetocarteira',
            index=models.Index(fields=['posicao_ranking'], name='projetos_ca_posicao_579f6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projetocarteira',
            unique_together={('carteira', 'projeto')},
        ),
        migrations.AddIndex(
            model_name='validacao',
            index=models.Index(fields=['carteira', 'status'], name='validacoes_carteir_0a0368_idx'),
        ),
    ]
