# Generated by Django 5.2 on 2026-04-07 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_create_superuser'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usuario',
            new_name='usuarios_perfil_ed19ca_idx',
            old_name='usuarios_perfil_idx',
        ),
        migrations.RenameIndex(
            model_name='usuario',
            new_name='usuarios_matricu_c31f98_idx',
            old_name='usuarios_matricula_idx',
        ),
    ]
