# Generated by Django 5.2 on 2026-04-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_usuarios_perfil_idx_usuarios_perfil_ed19ca_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhasePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('AVALIACAO', 'Avaliação'), ('VIABILIDADE', 'Viabilidade'), ('PRIORIZACAO', 'Priorização'), ('CONSOLIDACAO', 'Consolidação / adicionar projetos'), ('VALIDACAO', 'Validação de carteira'), ('DELIBERACAO', 'Deliberação da carteira')], max_length=20, unique=True)),
                ('allowed_perfis', models.CharField(help_text='Perfis permitidos separados por vírgula. Ex: SUPRN,GERENTE_PORTFOLIO', max_length=200)),
            ],
            options={
                'verbose_name': 'Permissão de Fase',
                'verbose_name_plural': 'Permissões de Fase',
                'db_table': 'phase_permissions',
            },
        ),
    ]
